/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  fabricspbm: [
    {
      type: 'autogenerated',
      dirName: 'fabricspbm',
    },
  ],
  fabricip: [
    {
      type: 'autogenerated',
      dirName: 'fabricip',
    },
  ],
  xiqse: [
    {
      type: 'autogenerated',
      dirName: 'xiqse',
    },
  ],
};

module.exports = sidebars;